name: flutter_crash_guard
description: State-management agnostic error handling mixin and Firebase Crashlytics integration with severity and categorization.
version: 2.0.0
repository: https://github.com/mohammedsajil/flutter_crash_guard
issue_tracker: https://github.com/mohammedsajil/flutter_crash_guard/issues
documentation: https://github.com/mohammedsajil/flutter_crash_guard#readme
license: BSD-3-Clause

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  hooks_riverpod: ^3.2.0
  dio: ^5.9.1
  firebase_core: ^4.4.0
  firebase_crashlytics: ^5.0.7
  package_info_plus: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
